// ui2/src/components/ui/ContextMenu.tsx
/**
 * ContextMenu
 *
 * Renders a global right-click menu from ContextMenuStore.
 */

import React, { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { useContextMenuStore } from '@/stores/contextMenuStore';
import { clampContextMenuPosition } from '@/utils/contextMenuPosition';
import { cn } from '@/utils/cn';

export function ContextMenu() {
  const isOpen = useContextMenuStore((s) => s.isOpen);
  const x = useContextMenuStore((s) => s.x);
  const y = useContextMenuStore((s) => s.y);
  const items = useContextMenuStore((s) => s.items);
  const close = useContextMenuStore((s) => s.close);

  const menuRef = useRef<HTMLDivElement>(null);
  const [menuSize, setMenuSize] = useState<{ width: number; height: number }>({ width: 0, height: 0 });

  useLayoutEffect(() => {
    if (!isOpen || !menuRef.current) return;
    const rect = menuRef.current.getBoundingClientRect();
    setMenuSize({ width: rect.width, height: rect.height });
  }, [isOpen, items.length]);

  useEffect(() => {
    if (!isOpen) return;

    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        close();
      }
    };

    document.addEventListener('keydown', handleEscape);
    return () => {
      document.removeEventListener('keydown', handleEscape);
    };
  }, [isOpen, close]);

  useEffect(() => {
    if (!isOpen) return;
    menuRef.current?.focus();
  }, [isOpen, items.length]);

  if (!isOpen) return null;

  const { left, top } =
    typeof window !== 'undefined'
      ? clampContextMenuPosition(
          x,
          y,
          menuSize,
          { width: window.innerWidth, height: window.innerHeight },
          6
        )
      : { left: x, top: y };

  return (
    <div
      className="fixed inset-0 z-50"
      role="presentation"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) {
          close();
        }
      }}
      onContextMenu={(e) => {
        e.preventDefault();
        close();
      }}
    >
      <div
        ref={menuRef}
        tabIndex={-1}
        role="menu"
        aria-orientation="vertical"
        className="absolute min-w-48 rounded-[1px] border border-border bg-card py-1 shadow-lg outline-none"
        style={{
          left,
          top,
        }}
      >
        {items.map((item) => {
          if (item.separator) {
            return (
              <hr
                key={item.id}
                className="my-1 border-border"
                role="separator"
              />
            );
          }

          const isDisabled = Boolean(item.disabled);

          return (
            <button
              key={item.id}
              type="button"
              role="menuitem"
              aria-disabled={isDisabled}
              className={cn(
                'flex w-full items-center gap-2 px-3 py-1.5 text-left text-[11px] font-mono uppercase tracking-wider transition-colors',
                isDisabled
                  ? 'cursor-not-allowed text-muted-foreground/50'
                  : item.danger
                    ? 'text-destructive hover:bg-destructive/10'
                    : 'text-foreground hover:bg-muted/50'
              )}
              disabled={isDisabled}
              onClick={() => {
                if (isDisabled) return;
                item.onClick?.();
                close();
              }}
            >
              {item.label}
            </button>
          );
        })}
      </div>
    </div>
  );
}

// ui/src/lib/components/ui/ContextMenu.svelte
<!--
  ContextMenu Component
  A reusable context menu that can be positioned at specific coordinates
-->
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { createEventDispatcher } from 'svelte';

	// Props
	let {
		visible = false,
		x = 0,
		y = 0,
		items = []
	}: {
		visible?: boolean;
		x?: number;
		y?: number;
		items?: Array<{
			label: string;
			icon?: any;
			action: () => void;
			divider?: boolean;
			disabled?: boolean;
		}>;
	} = $props();

	// Event dispatcher
	const dispatch = createEventDispatcher();

	// State
	let menuElement: HTMLDivElement | null = null;
	let adjustedX = $state(x);
	let adjustedY = $state(y);

	// Adjust position to ensure menu stays within viewport
	function adjustPosition() {
		if (!menuElement || !visible) return;

		const rect = menuElement.getBoundingClientRect();
		const viewportWidth = window.innerWidth;
		const viewportHeight = window.innerHeight;

		// Adjust X position
		if (x + rect.width > viewportWidth) {
			adjustedX = x - rect.width;
		} else {
			adjustedX = x;
		}

		// Adjust Y position
		if (y + rect.height > viewportHeight) {
			adjustedY = y - rect.height;
		} else {
			adjustedY = y;
		}
	}

	// Handle click outside
	function handleClickOutside(event: MouseEvent) {
		if (menuElement && !menuElement.contains(event.target as Node)) {
			dispatch('close');
		}
	}

	// Handle item click
	function handleItemClick(item: typeof items[0]) {
		if (!item.disabled) {
			item.action();
			dispatch('close');
		}
	}

	// Handle keyboard navigation
	function handleKeyDown(event: KeyboardEvent) {
		if (event.key === 'Escape') {
			dispatch('close');
		}
	}

	// Effects
	$effect(() => {
		if (visible) {
			adjustPosition();
			document.addEventListener('mousedown', handleClickOutside);
			document.addEventListener('keydown', handleKeyDown);
		} else {
			document.removeEventListener('mousedown', handleClickOutside);
			document.removeEventListener('keydown', handleKeyDown);
		}
	});

	// Lifecycle
	onDestroy(() => {
		document.removeEventListener('mousedown', handleClickOutside);
		document.removeEventListener('keydown', handleKeyDown);
	});
</script>

{#if visible}
	<div
		bind:this={menuElement}
		class="context-menu"
		style="left: {adjustedX}px; top: {adjustedY}px"
		role="menu"
		aria-label="Context menu"
	>
		{#each items as item, index}
			{#if item.divider}
				<div class="menu-divider" role="separator"></div>
			{:else}
				<button
					class="menu-item"
					class:disabled={item.disabled}
					onclick={() => handleItemClick(item)}
					disabled={item.disabled}
					role="menuitem"
					tabindex={item.disabled ? -1 : 0}
				>
					{#if item.icon}
						<svelte:component this={item.icon} size={14} class="menu-icon" />
					{/if}
					<span class="menu-label">{item.label}</span>
				</button>
			{/if}
		{/each}
	</div>
{/if}

<style>
	.context-menu {
		position: fixed;
		z-index: var(--z-popover, 1000);
		min-width: 160px;
		padding: var(--spacing-1);
		background-color: var(--color-surface-elevated);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-md);
		box-shadow: var(--shadow-lg);
		animation: fadeIn 150ms ease-out;
	}

	@keyframes fadeIn {
		from {
			opacity: 0;
			transform: translateY(-4px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	.menu-item {
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
		width: 100%;
		padding: var(--spacing-1) var(--spacing-2);
		background: none;
		border: none;
		border-radius: var(--radius-base);
		color: var(--color-text-primary);
		font-size: var(--font-size-sm);
		text-align: left;
		cursor: pointer;
		transition: all var(--transition-fast);
		user-select: none;
	}

	.menu-item:hover:not(.disabled) {
		background-color: var(--color-hover);
	}

	.menu-item:focus-visible {
		outline: 2px solid var(--color-border-focus);
		outline-offset: -2px;
	}

	.menu-item.disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	:global(.menu-icon) {
		flex-shrink: 0;
		opacity: 0.7;
	}

	.menu-label {
		flex: 1;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.menu-divider {
		height: 1px;
		margin: var(--spacing-1) 0;
		background-color: var(--color-border);
	}

	/* Dark theme adjustments */
	:global(.dark) .context-menu {
		background-color: var(--color-surface-900, #1a1a1a);
		border-color: var(--color-surface-700, #333);
	}
</style>
